name: Java CI Pipeline

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-test-format:
        runs-on: ubuntu-latest

        steps:
            - name: Repository auschecken
              uses: actions/checkout@v6

            - name: Java 25 einrichten
              uses: actions/setup-java@v5
              with:
                  distribution: 'temurin'
                  java-version: '25'
                  cache: 'gradle'

            - name: Gradle vorbereiten
              uses: gradle/actions/setup-gradle@v5

            - name: Gradle Wrapper ausführbar machen
              run: chmod +x ./gradlew

            - name: Projekt kompilieren
              run: ./gradlew compileJava --no-daemon

            - name: JUnit Tests ausführen
              run: ./gradlew test --no-daemon

            - name: Codeformatierung prüfen
              run: ./gradlew spotlessCheck --no-daemon
